#ifndef VERSION_H
#define VERSION_H

#define SATURNOS_NAME "SaturnOS"
#define SATURNOS_VERSION "0.6.90"
#define SATURNOS_VERSION_MAJOR 0UL
#define SATURNOS_VERSION_MINOR 6UL
#define SATURNOS_VERSION_PATCH 90UL
#define SATURNOS_CODENAME "Memory"

#endif
